/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ControladorSistema;

/**
 *
 * @author VICTOR
 */
public class VistaSistema extends javax.swing.JFrame {

    /**
     * Creates new form VistaSistema
     */
    public VistaSistema() {
        initComponents();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSistemaTitulo = new javax.swing.JLabel();
        btnSistemaVentas = new javax.swing.JButton();
        btnSistemaUsusarios = new javax.swing.JButton();
        btnSistemaBitacora = new javax.swing.JButton();
        btnSistemaProductos = new javax.swing.JButton();
        lblSistemaIcono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        lblSistemaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblSistemaTitulo.setText("Sistema");

        btnSistemaVentas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSistemaVentas.setText("VENTAS");
        btnSistemaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaVentasActionPerformed(evt);
            }
        });

        btnSistemaUsusarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSistemaUsusarios.setText("USUARIOS");
        btnSistemaUsusarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaUsusariosActionPerformed(evt);
            }
        });

        btnSistemaBitacora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSistemaBitacora.setText("BITACORA");
        btnSistemaBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaBitacoraActionPerformed(evt);
            }
        });

        btnSistemaProductos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSistemaProductos.setText("PRODUCTOS");
        btnSistemaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaProductosActionPerformed(evt);
            }
        });

        lblSistemaIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carne.png"))); // NOI18N
        lblSistemaIcono.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnSistemaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnSistemaUsusarios)
                        .addGap(27, 27, 27)
                        .addComponent(btnSistemaBitacora)
                        .addGap(30, 30, 30)
                        .addComponent(btnSistemaProductos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSistemaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSistemaIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblSistemaTitulo)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSistemaIcono)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSistemaVentas)
                    .addComponent(btnSistemaUsusarios)
                    .addComponent(btnSistemaBitacora)
                    .addComponent(btnSistemaProductos))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSistemaUsusariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaUsusariosActionPerformed
        System.out.println("Boton Usuarios");
        ControladorSistema.iniciarUsuarios();
    }//GEN-LAST:event_btnSistemaUsusariosActionPerformed

    private void btnSistemaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaVentasActionPerformed
        System.out.println("Boton Ventas");
        ControladorSistema.iniciarVentas();


    }//GEN-LAST:event_btnSistemaVentasActionPerformed

    private void btnSistemaBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaBitacoraActionPerformed
        System.out.println("Boton Bitacoras");
        ControladorSistema.iniciarBitacora();
    }//GEN-LAST:event_btnSistemaBitacoraActionPerformed

    private void btnSistemaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaProductosActionPerformed
        System.out.println("Boton Productos");
        ControladorSistema.iniciarProductos();
    }//GEN-LAST:event_btnSistemaProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSistema().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSistemaBitacora;
    private javax.swing.JButton btnSistemaProductos;
    private javax.swing.JButton btnSistemaUsusarios;
    private javax.swing.JButton btnSistemaVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSistemaIcono;
    private javax.swing.JLabel lblSistemaTitulo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnSistemaBitacora() {
        return btnSistemaBitacora;
    }

    public javax.swing.JButton getBtnSistemaProductos() {
        return btnSistemaProductos;
    }

    public javax.swing.JButton getBtnSistemaUsusarios() {
        return btnSistemaUsusarios;
    }

    public javax.swing.JButton getBtnSistemaVentas() {
        return btnSistemaVentas;
    }
}
